# Generated by Django 5.1.1 on 2024-10-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0003_remove_userprofile_birth_date_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
