# Generated by Django 5.1.1 on 2024-10-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0004_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
