# Generated by Django 5.1.1 on 2024-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0005_rename_username_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
