# Generated by Django 5.1.1 on 2024-10-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0009_alter_exercise_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_id',
        ),
    ]
