# Generated by Django 5.1.1 on 2024-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0010_remove_exercise_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
