# Generated by Django 5.1.1 on 2024-10-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0011_exercise_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='weight',
            new_name='weights',
        ),
    ]
