# Generated by Django 5.1.1 on 2024-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0012_rename_weight_performance_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
